# Generated by Django 4.2.3 on 2024-09-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_caption_budget_remove_sold_team_sold_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.BigIntegerField(default=300000),
        ),
    ]
