# Generated by Django 4.2.3 on 2024-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.URLField(),
        ),
    ]
